/**
 * GET /api/cron/tenant-isolation-scan — record the tenant-isolation coverage
 * metric into the learning loop.
 *
 * The repo-wide guardrail (src/lib/db/__tests__/tenant-isolation-global.test.ts)
 * proves at PR time that no query touches a workspace-scoped table without a
 * workspace_id predicate. This cron turns that one-time gate into a TIME SERIES:
 * every run persists a row in instinct_tenant_isolation_scans (migration 208)
 * AND emits `system.tenant_isolation_scanned`, so the learning loop can watch the
 * cross-tenant-leak gap (which must stay 0) and the benign-class breakdown trend
 * as the codebase grows. No data lost.
 *
 * WHY IT READS THE COMMITTED BASELINE rather than scanning source at runtime:
 * the scanner walks src/**.ts via fs, which is reliable at build/test time but
 * NOT in a Vercel serverless function (the .ts sources aren't in the deploy
 * bundle). The baseline JSON (regenerated by scripts/scan-tenant-isolation.ts and
 * committed; kept honest by the guardrail's drift test) IS bundled, so importing
 * it is deterministic and safe. The metric reflects the last green scan.
 *
 * Two auth paths (mirrors /api/cron/demo-canary + /api/cron/audit-log-verify):
 *   1. Cron path: `Authorization: Bearer ${CRON_SECRET}` (Vercel Cron).
 *   2. User path: `requireCapability(req, "settings.manage_team")` for an admin
 *      triggering a manual run.
 *
 * Never 500s on a recoverable condition: a DB write failure is swallowed (the
 * snapshot is best-effort telemetry, not a user action) and reported in the body.
 */

import { NextRequest, NextResponse } from "next/server";
import { safeQuery } from "@/lib/db";
import { trackEvent } from "@/lib/analytics";
import { requireCapability } from "@/lib/auth/require-capability";
import baseline from "@/lib/db/__generated__/tenant-isolation-baseline.json";

const ADMIN_CAPABILITY = "settings.manage_team" as const;

/** Cron secret check. Shared mental model with the other cron endpoints. Returns
 *  false when CRON_SECRET is unset (local dev) so the user-session path is the
 *  only way in. */
function isAuthorizedCron(req: NextRequest): boolean {
  const secret = process.env.CRON_SECRET;
  if (!secret) return false;
  return (req.headers.get("authorization") ?? "") === `Bearer ${secret}`;
}

async function recordScan(
  actorId: string,
  actorRole: string,
  source: "cron" | "manual",
): Promise<NextResponse> {
  const counts = (baseline.counts ?? {}) as Record<string, number>;
  const scopedTables = baseline.scopedTableCount ?? baseline.scopedTables?.length ?? 0;
  const enforcedTables = baseline.enforcedTableCount ?? baseline.enforcedTables?.length ?? 0;
  const totalOffenders = baseline.totalOffenders ?? 0;
  const unclassified = baseline.unclassifiedCount ?? 0;

  // Flatten the per-class counts into the analytics metadata (all numeric).
  const countMeta: Record<string, number> = {};
  for (const [k, v] of Object.entries(counts)) countMeta[`class_${k.replace(/-/g, "_")}`] = v;

  trackEvent("system.tenant_isolation_scanned", actorId, actorRole, {
    scoped_tables: scopedTables,
    // Retrofit progress: how many scoped tables have real FORCE-RLS enforcement
    // vs are still permissive tripwires. The whitepaper caveat lifts as this rises.
    rls_enforced_tables: enforcedTables,
    rls_tripwire_tables: scopedTables - enforcedTables,
    total_offenders: totalOffenders,
    unclassified,
    source,
    ...countMeta,
  });

  // Durable time-series row. Best-effort: safeQuery degrades to null on failure.
  const id = `tis_${new Date().toISOString()}`;
  const inserted = await safeQuery(
    `INSERT INTO instinct_tenant_isolation_scans
       (id, scoped_tables, total_offenders, unclassified, counts, source)
     VALUES ($1, $2, $3, $4, $5::jsonb, $6)
     ON CONFLICT (id) DO NOTHING`,
    [id, scopedTables, totalOffenders, unclassified, JSON.stringify(counts), source],
  );

  return NextResponse.json({
    ok: true,
    recorded: inserted !== null,
    scopedTables,
    enforcedTables,
    totalOffenders,
    unclassified,
    counts,
    source,
  });
}

export async function GET(req: NextRequest): Promise<NextResponse> {
  if (isAuthorizedCron(req)) {
    return recordScan("cron", "system", "cron");
  }
  const auth = await requireCapability(req, ADMIN_CAPABILITY);
  if (!auth.ok) return auth.response;
  return recordScan(auth.user.id, auth.user.role, "manual");
}
