-- 010_people.sql — People (HR) workspace.
--
-- Single sidebar entry for Alicia and leadership. Tables back the
-- Benefits sub-tab today; Employees / Onboarding / Documents extend
-- the same schema in follow-up passes.
--
-- Closed-loop: every CRUD action emits a tracked event in apex_events,
-- and every recommendation generated is stored as a row so the brain
-- can learn which suggestions get accepted vs rejected over time.

-- Master employee record (basic shape; extends in follow-up).
CREATE TABLE IF NOT EXISTS apex_employees (
  id            TEXT PRIMARY KEY,
  full_name     TEXT NOT NULL,
  email         TEXT UNIQUE,
  role_title    TEXT,
  department    TEXT,
  start_date    DATE,
  birth_year    INTEGER,
  zip_code      TEXT,
  status        TEXT NOT NULL DEFAULT 'active',  -- active|onboarding|terminated
  metadata      JSONB DEFAULT '{}'::jsonb,
  created_by    TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_apex_employees_status ON apex_employees(status);

-- Source benefit documents (PDFs uploaded from carriers/brokers).
CREATE TABLE IF NOT EXISTS apex_benefit_documents (
  id              TEXT PRIMARY KEY,
  filename        TEXT NOT NULL,
  carrier         TEXT,
  effective_date  DATE,
  account_number  TEXT,
  page_count      INTEGER,
  size_bytes      INTEGER NOT NULL,
  raw_text_excerpt TEXT,
  uploaded_by     TEXT NOT NULL,
  uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Parsed plan rows extracted from a document.
CREATE TABLE IF NOT EXISTS apex_benefit_plans (
  id                TEXT PRIMARY KEY,
  document_id       TEXT REFERENCES apex_benefit_documents(id) ON DELETE CASCADE,
  plan_id           TEXT NOT NULL,             -- carrier code, e.g. S9N1ADT
  plan_name         TEXT,                      -- "Blue Advantage HMO Silver"
  network           TEXT,                      -- HMO|PPO|EPO etc.
  metal_tier        TEXT,                      -- Platinum|Gold|Silver|Bronze
  is_hsa            BOOLEAN NOT NULL DEFAULT FALSE,
  individual_deductible_in_network NUMERIC,
  individual_deductible_out_of_network NUMERIC,
  individual_oop_max_in_network NUMERIC,
  individual_oop_max_out_of_network NUMERIC,
  primary_care_copay TEXT,                     -- raw, e.g. "$0/$0" or "DC/DC"
  primary_care_copay_in_network NUMERIC,       -- normalized: 0 if $0, NULL if DC
  specialist_copay  TEXT,
  specialist_copay_in_network NUMERIC,
  er_copay          TEXT,
  rx_copays         TEXT,                      -- raw rx tier string
  monthly_premium_age_employee_only NUMERIC,
  monthly_premium_composite_employee_only NUMERIC,
  monthly_premium_age_employee_spouse NUMERIC,
  monthly_premium_age_employee_child NUMERIC,
  monthly_premium_age_employee_family NUMERIC,
  raw                JSONB NOT NULL,           -- full extracted row for replay
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_apex_benefit_plans_doc ON apex_benefit_plans(document_id);
CREATE INDEX IF NOT EXISTS idx_apex_benefit_plans_premium ON apex_benefit_plans(monthly_premium_age_employee_only);

-- Recommendations generated by the scoring engine. Stored so the brain
-- learns which recommendations are accepted vs rejected.
CREATE TABLE IF NOT EXISTS apex_benefit_recommendations (
  id              TEXT PRIMARY KEY,
  document_id     TEXT REFERENCES apex_benefit_documents(id) ON DELETE CASCADE,
  rule_name       TEXT NOT NULL,                  -- "cheapest_practical", "lowest_premium", etc.
  recommended_plan_id TEXT NOT NULL,              -- carrier plan id (e.g. S9N1ADT)
  reasoning       TEXT,
  score_breakdown JSONB,
  outcome         TEXT NOT NULL DEFAULT 'pending', -- pending|accepted|rejected|ignored
  decided_by      TEXT,
  decided_at      TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_apex_benefit_recs_doc ON apex_benefit_recommendations(document_id);

-- Programmatic insights surfaced on the People > Insights tab.
CREATE TABLE IF NOT EXISTS apex_hr_insights (
  id            TEXT PRIMARY KEY,
  category      TEXT NOT NULL,                  -- "benefits"|"onboarding"|"compliance"
  severity      TEXT NOT NULL DEFAULT 'info',   -- info|attention|critical
  title         TEXT NOT NULL,
  body          TEXT NOT NULL,
  related_id    TEXT,                           -- plan_id, employee_id, etc.
  source_rule   TEXT,                           -- which rule produced this
  status        TEXT NOT NULL DEFAULT 'open',   -- open|viewed|dismissed|acted
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at   TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_apex_hr_insights_status ON apex_hr_insights(status);
