/**
 * Remediation PR: turn an accepted recommendation into a review-gated pull
 * request on the target repo. The PR is the human checkpoint, so this NEVER
 * merges and never pushes to the base branch: it creates a branch, commits a
 * precise remediation spec (the finding, the exact fix, acceptance criteria,
 * and the re-scan note), and opens a PR an engineer reviews.
 *
 * Deliberately deterministic content (no LLM code-gen): a spec doc is always
 * correct and never ships broken code into a client repo. Concrete code patches
 * for high-confidence, framework-detected fixes are a clearly-scoped later tier
 * that plugs into buildRemediationPlan's `files`.
 *
 * Governed: every PR is run through the OGIAM gate (monitor mode in Phase 0, so
 * the decision is recorded to the tamper-evident ledger for audit + learning;
 * graduating to enforce is a config change, not a code change here) and audited
 * by the caller.
 */
import {
  type GithubClient,
  defaultGithubClient,
  createBranch,
  putFile,
  openPullRequest,
} from "@/lib/github-client";
import { authorize } from "@/lib/ogiam/authorize";
import type { OgiamDecision } from "@/lib/ogiam/types";
import type { RecommendationRow } from "./store";

const slug = (s: string): string => s.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "").toLowerCase();

export interface RemediationPlan {
  branch: string;
  files: { path: string; content: string }[];
  title: string;
  body: string;
}

/** Build the deterministic PR plan for a recommendation. Pure: no I/O. */
export function buildRemediationPlan(rec: RecommendationRow, baseBranch: string): RemediationPlan {
  const keySlug = slug(rec.key);
  const branch = `ogiam/remediate-${keySlug}-${rec.id.slice(0, 8)}`;
  const docPath = `docs/remediation/${keySlug}.md`;
  const evidence = Object.entries(rec.evidence ?? {})
    .map(([k, v]) => `- ${k}: ${String(v)}`)
    .join("\n") || "- (none recorded)";

  const doc = [
    `# Remediation: ${rec.title}`,
    ``,
    `> Generated by OGIAM from a ${rec.priority} ${rec.category} recommendation on \`${rec.platform}\`.`,
    `> This branch is for review. Do not merge without an engineer's approval.`,
    ``,
    `## Why`,
    ``,
    rec.rationale,
    ``,
    `## Fix`,
    ``,
    rec.suggestedAction,
    ``,
    `## Evidence`,
    ``,
    evidence,
    ``,
    `## Acceptance criteria`,
    ``,
    `- The fix above is applied.`,
    `- A re-scan of \`${rec.platform}\` no longer reports this finding (it auto-resolves).`,
    ``,
    `_Source: ${rec.source} · key: ${rec.key}_`,
    ``,
  ].join("\n");

  const body = [
    `Automated remediation proposal from OGIAM.`,
    ``,
    `**Recommendation:** ${rec.title} (${rec.priority} ${rec.category})`,
    ``,
    `**Why:** ${rec.rationale}`,
    ``,
    `**Fix:** ${rec.suggestedAction}`,
    ``,
    `This PR documents the remediation under \`${docPath}\`. Review and apply the fix, then re-scan ${rec.platform} to confirm it auto-resolves. OGIAM does not merge: this is the human checkpoint.`,
  ].join("\n");

  return {
    branch,
    files: [{ path: docPath, content: doc }],
    title: `OGIAM remediation: ${rec.title}`,
    body,
  };
}

export interface RemediationResult {
  prUrl: string;
  prNumber: number;
  branch: string;
  decision: OgiamDecision;
}

export interface OpenRemediationInput {
  rec: RecommendationRow;
  repoFullName: string;
  baseBranch: string;
  workspaceId: string;
  actor: { userId: string; role: string };
}

/**
 * Open the review-gated remediation PR. Runs the gate first (records the decision
 * to the OGIAM ledger), then branch -> commit spec -> open PR. In enforce mode a
 * blocking decision short-circuits before any write; in monitor mode (Phase 0) it
 * records and proceeds, since the PR itself is the review gate.
 */
export async function openRemediationPR(
  input: OpenRemediationInput,
  client: GithubClient = defaultGithubClient(),
): Promise<RemediationResult> {
  const plan = buildRemediationPlan(input.rec, input.baseBranch);

  const decision = await authorize({
    principal: {
      kind: "ai_agent",
      agent: "instinct.remediation",
      onBehalfOfUserId: input.actor.userId,
      onBehalfOfRole: input.actor.role,
      workspaceId: input.workspaceId,
    },
    tool: "remediation.open_pr",
    capability: "platform.remediate",
    isMutation: true,
    surface: "/agent",
    params: { repo: input.repoFullName, branch: plan.branch, key: input.rec.key },
    mode: "monitor",
  });

  // In enforce mode, a gate that actually blocks must stop before any write.
  if (decision.enforced && decision.effectiveOutcome !== "allow") {
    throw new Error(`gate_blocked: ${decision.ruleId} (${decision.reason})`);
  }

  await createBranch(client, input.repoFullName, plan.branch, input.baseBranch);
  for (const f of plan.files) {
    await putFile(client, input.repoFullName, f.path, f.content, `OGIAM remediation: ${input.rec.title}`, plan.branch);
  }
  const pr = await openPullRequest(client, input.repoFullName, plan.branch, input.baseBranch, plan.title, plan.body);

  return { prUrl: pr.html_url, prNumber: pr.number, branch: plan.branch, decision };
}
