/**
 * Catch blocks in the answer path that destroy the evidence of a failure.
 *
 * A catch that returns an empty array turns "the query threw" into "there were
 * no results", and every layer above it then reports the absence honestly.
 * Chasing exactly that cost an afternoon and five discarded hypotheses. The
 * judgment lives in src/lib/ci/silent-catch.ts and is tested there; this
 * walks the files and holds the ratchet.
 *
 *   npm run scan:silent-catches
 *   npm run scan:silent-catches -- --write   # move the baseline (only down)
 *
 * A RATCHET, NOT A WALL. There are dozens already. Failing on all of them
 * would mean the check gets turned off within a day, so the committed count
 * may fall and may not rise.
 */
import fs from "node:fs";
import path from "node:path";
import { readCatches } from "@/lib/ci/silent-catch";

const REPO = path.resolve(__dirname, "..");
const BASELINE = path.join(REPO, "src/lib/ci/__generated__/silent-catch-baseline.json");

/**
 * The answer path, and only it.
 *
 * Scoped deliberately. A repo-wide number would be large, mostly irrelevant,
 * and would never move. These are the directories where a swallowed error
 * becomes a wrong answer in front of a client.
 */
const ROOTS = ["src/lib/assistant", "src/lib/brain", "src/lib/search", "src/lib/ai"];

function walk(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) return e.name === "__tests__" ? [] : walk(full);
    return /\.tsx?$/.test(e.name) && !/\.test\.tsx?$/.test(e.name) ? [full] : [];
  });
}

function main() {
  const files = ROOTS.flatMap((r) => walk(path.join(REPO, r))).map((f) => ({
    path: path.relative(REPO, f),
    source: fs.readFileSync(f, "utf-8"),
  }));

  const reading = readCatches(files);
  const total = reading.verdicts.length;

  console.log(`${files.length} files in the answer path, ${total} catch blocks.\n`);
  console.log(`  reports a failure    ${String(reading.reports.length).padStart(4)}`);
  console.log(`  declared quiet       ${String(reading.declared.length).padStart(4)}`);
  console.log(`  SILENT               ${String(reading.silent.length).padStart(4)}\n`);

  const byFile = new Map<string, number>();
  for (const v of reading.silent) byFile.set(v.site.file, (byFile.get(v.site.file) ?? 0) + 1);
  for (const [file, n] of [...byFile].sort((a, b) => b[1] - a[1]).slice(0, 12)) {
    console.log(`  ${String(n).padStart(3)}  ${file}`);
  }

  if (process.argv.includes("--write")) {
    fs.mkdirSync(path.dirname(BASELINE), { recursive: true });
    fs.writeFileSync(
      BASELINE,
      JSON.stringify(
        {
          note:
            "Generated by scripts/scan-silent-catches.ts. A ratchet: silentCount may FALL and may not rise. " +
            "Do not edit by hand; run the script with --write after removing silent catches.",
          silentCount: reading.silent.length,
          declaredCount: reading.declared.length,
          files: [...byFile].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).map(([file, count]) => ({ file, count })),
        },
        null,
        2,
      ) + "\n",
    );
    console.log(`\nwrote baseline -> ${path.relative(REPO, BASELINE)}`);
    return;
  }

  if (!fs.existsSync(BASELINE)) {
    console.log("\nNo baseline yet. Run with --write to record one.");
    return;
  }

  const baseline = JSON.parse(fs.readFileSync(BASELINE, "utf-8")) as { silentCount: number };
  if (reading.silent.length > baseline.silentCount) {
    console.error(
      `\nRATCHET: ${reading.silent.length} silent catches, baseline is ${baseline.silentCount}.\n` +
        `Report the failure (a log, trackEvent, a degradation note, a rethrow), or mark it\n` +
        `deliberately quiet with a reason:  /* silent-ok: why this one is fine */`,
    );
    process.exit(1);
  }
  console.log(
    `\nsilent: ${reading.silent.length} (baseline ${baseline.silentCount})` +
      (reading.silent.length < baseline.silentCount
        ? " — improved; run with --write to lower the ratchet."
        : " — held."),
  );
}

main();
