/**
 * scripts/scan-tenant-isolation.ts
 *
 * Repo-wide multi-tenant isolation report. Walks every SQL literal in src/ and
 * flags filtering queries on a workspace-scoped table that lack a workspace_id
 * predicate, classifying each into a benign class or "unclassified" (a real
 * cross-tenant leak). Shares its core with the PR-gating guardrail test and the
 * /api/cron/tenant-isolation-scan learning hook — all import
 * src/lib/db/tenant-scope-scan.ts, so there is exactly one source of truth.
 *
 * Usage:
 *   npx tsx scripts/scan-tenant-isolation.ts          # print the report
 *   npx tsx scripts/scan-tenant-isolation.ts --write   # also (re)write the
 *                                                       # committed baseline JSON
 *
 * Exit code is 1 when any "unclassified" offender exists, so CI can run this
 * standalone as a gate in addition to the jest guardrail.
 */
import fs from "fs";
import path from "path";
import { scanRepo, type OffenderClass } from "../src/lib/db/tenant-scope-scan";

const REPO_ROOT = path.resolve(__dirname, "..");
const BASELINE = path.join(REPO_ROOT, "src/lib/db/__generated__/tenant-isolation-baseline.json");

/** The committed, deterministic baseline: NO timestamps (would churn git). The
 *  cron stamps its own observed_at at runtime when it records the snapshot. */
export interface TenantIsolationBaseline {
  note: string;
  scopedTableCount: number;
  scopedTables: string[];
  filesScanned: number;
  filesTouchingScoped: number;
  totalOffenders: number;
  counts: Record<OffenderClass, number>;
  unclassifiedCount: number;
}

function buildBaseline(): TenantIsolationBaseline {
  const r = scanRepo(REPO_ROOT);
  return {
    note: "Generated by scripts/scan-tenant-isolation.ts. Do not edit by hand; run the script with --write. unclassifiedCount MUST be 0.",
    scopedTableCount: r.scopedTables.length,
    scopedTables: r.scopedTables,
    filesScanned: r.filesScanned,
    filesTouchingScoped: r.filesTouchingScoped,
    totalOffenders: r.offenders.length,
    counts: r.counts,
    unclassifiedCount: r.unclassified.length,
  };
}

function main() {
  const r = scanRepo(REPO_ROOT);
  console.log("=== tenant-isolation scan ===");
  console.log(`workspace-scoped tables: ${r.scopedTables.length}`);
  console.log(`source files scanned:    ${r.filesScanned} (${r.filesTouchingScoped} touch a scoped table)`);
  console.log(`offenders (no static workspace_id predicate): ${r.offenders.length}`);
  for (const [klass, n] of Object.entries(r.counts)) {
    if (n > 0) console.log(`   ${klass.padEnd(24)} ${n}`);
  }
  if (r.unclassified.length > 0) {
    console.error(`\nCROSS-TENANT LEAK: ${r.unclassified.length} unclassified offender(s):`);
    for (const o of r.unclassified) {
      console.error(`  ${o.file} [${o.table}] ${o.kind}\n    ${o.snippet}`);
    }
  } else {
    console.log("\nunclassified: 0 — every scoped query is filtered or a documented benign class.");
  }

  if (process.argv.includes("--write")) {
    fs.mkdirSync(path.dirname(BASELINE), { recursive: true });
    fs.writeFileSync(BASELINE, JSON.stringify(buildBaseline(), null, 2) + "\n");
    console.log(`\nwrote baseline -> ${path.relative(REPO_ROOT, BASELINE)}`);
  }

  process.exit(r.unclassified.length > 0 ? 1 : 0);
}

main();
